version: '3'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: app-php
        restart: always
        ports:
            - 8080:8000
        volumes:
            - .:/app
